### ISSUE TITLE
Update ESP32 builds to use ESP32 Arduino 2.0.3-RC1 based on ESP-IDF 4.4

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Wippersnapper_Arduino#242]
[Arduino ESP32 version 2.0.3 based on the ESP-IDF v4.4 introduces the support for the ESP32-S3, new boards support, new APIs, refactoring, improvements, and bug fixes](https://github.com/espressif/arduino-esp32/releases). 

**TO-DO**
- [x] Remove _daily key from the build script (https://github.com/adafruit/ci-arduino/pull/125)
- [x] Remove `feather_esp32_v2_daily` from [the build script](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/.github/workflows/build-clang-doxy.yml) and change it to `feather_esp32_v2` since this hardware is now included within ESP32 Arduino 2.0.3-RC1.
- [x] This should automatically be built with the release of beta 30 as 2.0.3-RC1 is within the release channel as the latest release, however, we'll want to test releasing this on a fork to ensure this is the case.

**Comment by brentru** [comment]
Tested in https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/249, closing
