### ISSUE TITLE
Update Wippersnapper_DigitalGPIO class for V2 API

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Wippersnapper_Arduino#624]
Refactor the `Wippersnapper_DigitalGPIO` class to support the V2 API using the new Protocol Buffer messages. This update is part of a broader effort to align this Wippersnapper library with the latest API version, as discussed in #613 

**Tasks:**
- [x] Interface the top-level Signal decoder  with each sub-message type
- [x] Implement `model` class for interfacing with [digitalio.proto](https://github.com/adafruit/Wippersnapper_Protobuf/blob/api-v2/proto/wippersnapper/digitalio.proto)
- [x] Implement `controller` class for interfacing with decoded PB messages 
- [x] Implement `hardware` class for interfacing with device hardware
  - [x] Refactor existing `Wippersnapper_DigitalGPIO` class first
- [x] Test the updated class for functionality and stability (long-term test)
